### ISSUE TITLE
Navigating to /static results in infinite redirection loop

### ISSUE THREAD

**Issue by rebo** [MartinKavik/kavik.cz#1]
Not that one would choose to navigate there, but I assume you don't want that behaviour.

**Comment by MartinKavik** [comment]
Good catch! How did you find it?

There was an ugly workaround which I've deleted thanks to https://github.com/David-OConnor/seed/pull/221. The whole repo is refactored (because I want to use it as the base for a new version of `quickstart-webpack`), so I've "accidentally" resolved this issue.

**Comment by rebo** [comment]
>Good catch! How did you find it?

Just experimenting to figure out how the routing worked :) Giving things a poke etc.
